### ISSUE TITLE
add algorithm which which is not  in my repo  , give star to repo also 

### ISSUE THREAD

**Issue by FRAGxTITAN** [FRAGxTITAN/data-structures-and-algorithms-#1]

**Comment by vishwadere** [comment]
Please assign me this Issue under Hacktoberfest 2022 after adding necessary labels.

**Comment by harshmohan2905** [comment]
bro just contibute in Data structure and algo repo just add your code as it is public repo i will merge it @vishwadere

**Comment by FRAGxTITAN** [comment]
@vishwadere bro repo is public just add code in repo  there i will merge the code
